Ingredient.create!([
  {name: "Butter"},
  {name: "Olive Oil"},
  {name: "Salt"},
  {name: "Pepper"},
  {name: "Sugar"},
  {name: "Papricka"},
  {name: "Cinnamon"},
  {name: "Flour"},
  {name: "Basil"},
  {name: "Rosemary"},
  {name: "Thyme"},
  {name: "Garlic"},
  {name: "Jalapeno"},
  {name: "Onion"},
  {name: "Tomato"},
  {name: "Potato"},
  {name: "Green Pepper"},
  {name: "Carrots"},
  {name: "Lemon"},
  {name: "Apple"},
  {name: "Spagetti"},
  {name: "Bread Crumbs"},
  {name: "Chicken Stock"},
  {name: "Ground Beef"},
  {name: "Chicken Breast"},
  {name: "Pork Shoulder"},
  {name: "Cubed Steak"}
])
PantryIngredient.create!([
  {ingredient_id: 1, user_id: 1, measurement: 2},
  {ingredient_id: 2, user_id: 1, measurement: 2},
  {ingredient_id: 3, user_id: 1, measurement: 1},
  {ingredient_id: 4, user_id: 1, measurement: 1},
  {ingredient_id: 5, user_id: 1, measurement: 1},
  {ingredient_id: 6, user_id: 1, measurement: 1},
  {ingredient_id: 7, user_id: 1, measurement: 1},
  {ingredient_id: 8, user_id: 1, measurement: 1},
  {ingredient_id: 9, user_id: 1, measurement: 3},
  {ingredient_id: 10, user_id: 1, measurement: 3},
  {ingredient_id: 11, user_id: 1, measurement: 2},
  {ingredient_id: 12, user_id: 1, measurement: 3},
  {ingredient_id: 13, user_id: 1, measurement: 3},
  {ingredient_id: 14, user_id: 1, measurement: 3},
  {ingredient_id: 15, user_id: 1, measurement: 3},
  {ingredient_id: 16, user_id: 1, measurement: 3},
  {ingredient_id: 17, user_id: 1, measurement: 3},
  {ingredient_id: 18, user_id: 1, measurement: 3},
  {ingredient_id: 19, user_id: 1, measurement: 3},
  {ingredient_id: 20, user_id: 1, measurement: 4},
  {ingredient_id: 21, user_id: 1, measurement: 4},
  {ingredient_id: 22, user_id: 1, measurement: 5},
  {ingredient_id: 23, user_id: 1, measurement: 7},
  {ingredient_id: 24, user_id: 1, measurement: 7},
  {ingredient_id: 25, user_id: 1, measurement: 7}
])
Recipe.create!([
  {name: "Chicken and Potatoes"},
  {name: "Pot Roast"},
  {name: "Spagetti and Meatballs"},
  {name: "Pork Stew"},
  {name: "Chicken Alfredo"},
  {name: "Smothered Chicken"},
  {name: "Chicken Fried Steak"},
  {name: "Swedish Meatballs"},
  {name: "Pork Roast and Potatoes"}
])
RecipeIngredient.create!([
  {recipe_id: 1, ingredient_id: 1, measurement: 2},
  {recipe_id: 1, ingredient_id: 3, measurement: 1},
  {recipe_id: 1, ingredient_id: 4, measurement: 1},
  {recipe_id: 1, ingredient_id: 6, measurement: 1},
  {recipe_id: 1, ingredient_id: 12, measurement: 3},
  {recipe_id: 1, ingredient_id: 14, measurement: 3},
  {recipe_id: 1, ingredient_id: 16, measurement: 3},
  {recipe_id: 1, ingredient_id: 23, measurement: 7},
  {recipe_id: 2, ingredient_id: 1, measurement: 2},
  {recipe_id: 2, ingredient_id: 3, measurement: 1},
  {recipe_id: 2, ingredient_id: 4, measurement: 1},
  {recipe_id: 2, ingredient_id: 10, measurement: 3},
  {recipe_id: 2, ingredient_id: 11, measurement: 2},
  {recipe_id: 2, ingredient_id: 15, measurement: 3},
  {recipe_id: 2, ingredient_id: 22, measurement: 5},
  {recipe_id: 2, ingredient_id: 25, measurement: 7},
  {recipe_id: 3, ingredient_id: 2, measurement: 2},
  {recipe_id: 3, ingredient_id: 3, measurement: 1},
  {recipe_id: 3, ingredient_id: 4, measurement: 1},
  {recipe_id: 3, ingredient_id: 14, measurement: 3},
  {recipe_id: 3, ingredient_id: 15, measurement: 3},
  {recipe_id: 3, ingredient_id: 19, measurement: 3},
  {recipe_id: 3, ingredient_id: 20, measurement: 4},
  {recipe_id: 3, ingredient_id: 22, measurement: 7},
  {recipe_id: 4, ingredient_id: 1, measurement: 2},
  {recipe_id: 4, ingredient_id: 3, measurement: 1},
  {recipe_id: 4, ingredient_id: 4, measurement: 1},
  {recipe_id: 4, ingredient_id: 10, measurement: 3},
  {recipe_id: 4, ingredient_id: 11, measurement: 2},
  {recipe_id: 4, ingredient_id: 25, measurement: 7},
  {recipe_id: 4, ingredient_id: 26, measurement: 7},
  {recipe_id: 4, ingredient_id: 27, measurement: 7}
])
User.create!([
  {name: "nate", email: "nate@gmail.com", password_digest: "$2a$10$4gSUVfClee6sWC6PhE6CZODyjxobvl/1W02NfP5JOTJ5cgs4521hO"}
])
CookBook.create!([
  {user_id: 1}
])
CookBookRecipe.create!([
  {recipe_id: 1, cook_book_id: 1, rating: 5}
])