Category.create!([
  {aisle: "Milk, Eggs, Other Dairy"},
  {aisle: "Oil, Vinegar, Salad Dressing"},
  {aisle: "Spices and Seasonings"},
  {aisle: "Baking"},
  {aisle: "Produce"},
  {aisle: "Pasta and Rice"},
  {aisle: "Canned and Jarred"},
  {aisle: "Cheese"},
  {aisle: "Meat"}
])
Ingredient.create!([
  {name: "Olive Oil", category_id: 2},
  {name: "Dijon Mustard", category_id: 2},
  {name: "Soy Sauce", category_id: 2},
  {name: "Sesame Oil", category_id: 2},
  {name: "Apple Cider Vinegar", category_id: 2},
  {name: "Canned Tomatoes", category_id: 7},
  {name: "Canned Jalepenos", category_id: 7},
  {name: "Chicken Broth", category_id: 7},
  {name: "Flour", category_id: 4},
  {name: "Panko Bread Crumbs", category_id: 4},
  {name: "Spagetti", category_id: 6},
  {name: "Lasagna Noodes", category_id: 6},
  {name: "Ziti", category_id: 6},
  {name: "Brown Rice", category_id: 6},
  {name: "Salt", category_id: 3},
  {name: "Pepper", category_id: 3},
  {name: "Sugar", category_id: 3},
  {name: "Papricka", category_id: 3},
  {name: "Cinnamon", category_id: 3},
  {name: "Basil", category_id: 3},
  {name: "Thyme", category_id: 3},
  {name: "Curry Powder", category_id: 3},
  {name: "Dried Oregano", category_id: 3},
  {name: "Rosemary", category_id: 5},
  {name: "Garlic", category_id: 5},
  {name: "Jalapeno", category_id: 5},
  {name: "Onion", category_id: 5},
  {name: "Tomato", category_id: 5},
  {name: "Potato", category_id: 5},
  {name: "Green Pepper", category_id: 5},
  {name: "Carrots", category_id: 5},
  {name: "Lemon", category_id: 5},
  {name: "Apple", category_id: 5},
  {name: "Cilantro", category_id: 5},
  {name: "Ginger", category_id: 5},
  {name: "Celery", category_id: 5},
  {name: "Taragon", category_id: 5},
  {name: "Sweet Potato", category_id: 5},
  {name: "Fresh Oregano", category_id: 5},
  {name: "Bok Choy", category_id: 5},
  {name: "Zucchini", category_id: 5},
  {name: "Calliflower", category_id: 5},
  {name: "Red-Skinned Potatoes", category_id: 5},
  {name: "Parmesan Cheese", category_id: 8},
  {name: "Ricotta Cheese", category_id: 8},
  {name: "Romano Cheese", category_id: 8},
  {name: "Eggs", category_id: 1},
  {name: "Heavy Cream", category_id: 1},
  {name: "Butter", category_id: 1},
  {name: "Ground Beef", category_id: 9},
  {name: "Chicken Breast", category_id: 9},
  {name: "Pork Shoulder", category_id: 9},
  {name: "Skirt Steak", category_id: 9}
])
Measurement.create!([
  {unit: " "},
  {unit: "serving"},
  {unit: "teaspoon"},
  {unit: "tablespoon"},
  {unit: "cup"},
  {unit: "fluid ounce"},
  {unit: "teaspoon"},
  {unit: "pint"},
  {unit: "quart"},
  {unit: "gallon"},
  {unit: "ounce"},
  {unit: "pound"}
])
User.create!([
  {name: "nate", email: "nate@gmail.com", password_digest: "$2a$10$4gSUVfClee6sWC6PhE6CZODyjxobvl/1W02NfP5JOTJ5cgs4521hO", phone: "+13128524472"}
])
PantryIngredient.create!([
  {ingredient_id: 1, user_id: 1, measurement_id: 3, amount: "16.0"},
  {ingredient_id: 2, user_id: 1, measurement_id: 9, amount: "1.0"},
  {ingredient_id: 3, user_id: 1, measurement_id: 7, amount: "2.0"},
  {ingredient_id: 4, user_id: 1, measurement_id: 4, amount: "50.0"},
  {ingredient_id: 5, user_id: 1, measurement_id: 4, amount: "50.0"},
  {ingredient_id: 6, user_id: 1, measurement_id: 4, amount: "10.0"},
  {ingredient_id: 7, user_id: 1, measurement_id: 4, amount: "5.0"},
  {ingredient_id: 8, user_id: 1, measurement_id: 4, amount: "2.0"},
  {ingredient_id: 9, user_id: 1, measurement_id: 4, amount: "2.0"},
  {ingredient_id: 10, user_id: 1, measurement_id: 3, amount: "5.0"},
  {ingredient_id: 11, user_id: 1, measurement_id: 4, amount: "15.0"},
  {ingredient_id: 12, user_id: 1, measurement_id: 4, amount: "25.0"},
  {ingredient_id: 13, user_id: 1, measurement_id: 1, amount: "2.0"},
  {ingredient_id: 14, user_id: 1, measurement_id: 1, amount: "3.0"},
  {ingredient_id: 15, user_id: 1, measurement_id: 11, amount: "5.0"},
  {ingredient_id: 16, user_id: 1, measurement_id: 1, amount: "2.0"},
  {ingredient_id: 17, user_id: 1, measurement_id: 1, amount: "3.0"},
  {ingredient_id: 18, user_id: 1, measurement_id: 1, amount: "2.0"},
  {ingredient_id: 19, user_id: 1, measurement_id: 1, amount: "2.0"},
  {ingredient_id: 20, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 21, user_id: 1, measurement_id: 1, amount: "5.0"},
  {ingredient_id: 22, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 23, user_id: 1, measurement_id: 1, amount: "5.0"},
  {ingredient_id: 24, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 25, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 26, user_id: 1, measurement_id: 4, amount: "5.0"},
  {ingredient_id: 27, user_id: 1, measurement_id: 4, amount: "5.0"},
  {ingredient_id: 28, user_id: 1, measurement_id: 4, amount: "5.0"},
  {ingredient_id: 29, user_id: 1, measurement_id: 1, amount: "12.0"},
  {ingredient_id: 30, user_id: 1, measurement_id: 8, amount: "1.0"},
  {ingredient_id: 31, user_id: 1, measurement_id: 11, amount: "1.0"},
  {ingredient_id: 32, user_id: 1, measurement_id: 11, amount: "2.0"},
  {ingredient_id: 33, user_id: 1, measurement_id: 11, amount: "8.0"},
  {ingredient_id: 34, user_id: 1, measurement_id: 11, amount: "5.0"},
  {ingredient_id: 35, user_id: 1, measurement_id: 11, amount: "0.25"},
  {ingredient_id: 36, user_id: 1, measurement_id: 4, amount: "5.0"},
  {ingredient_id: 37, user_id: 1, measurement_id: 4, amount: "1.0"},
  {ingredient_id: 38, user_id: 1, measurement_id: 1, amount: "2.0"},
  {ingredient_id: 39, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 40, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 41, user_id: 1, measurement_id: 1, amount: "2.0"},
  {ingredient_id: 42, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 43, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 44, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 45, user_id: 1, measurement_id: 5, amount: "6.0"},
  {ingredient_id: 46, user_id: 1, measurement_id: 5, amount: "8.0"},
  {ingredient_id: 47, user_id: 1, measurement_id: 11, amount: "0.25"},
  {ingredient_id: 48, user_id: 1, measurement_id: 11, amount: "0.25"},
  {ingredient_id: 49, user_id: 1, measurement_id: 3, amount: "5.0"},
  {ingredient_id: 50, user_id: 1, measurement_id: 1, amount: "1.0"},
  {ingredient_id: 51, user_id: 1, measurement_id: 1, amount: "8.0"},
  {ingredient_id: 52, user_id: 1, measurement_id: 4, amount: "12.0"},
  {ingredient_id: 53, user_id: 1, measurement_id: 1, amount: "8.0"}
])
